apiVersion: v1
kind: Secret
metadata:
  name: cohort2-app-secret
  namespace: cohort-dev
type: Opaque
data:
  # example how we can store secret
  # echo -n "dev-secret" | base64
  APP_SECRET_KEY: bm9uLXByb2Qtc2VjcmV0