apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cohort2-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  APP_VERSION: {{ .Values.config.APP_VERSION | quote }}
  APP_PORT: {{ .Values.config.APP_PORT | quote }}
  APP_ENVIRONMENT: {{ .Values.config.APP_ENVIRONMENT | quote }}