apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cohort2-app.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  APP_SECRET_KEY: {{ .Values.secret.appSecretKey | b64enc | quote }}